spring:
  kafka:
    bootstrap-servers: broker:9092
    client-id: wordsnake

app:
  streams-config:
    application-id: wordsnake-0.1
    input-topic: input
    output-raw-topic: output_raw
    output-processed-topic: output_processed
    error-topic: error
    allow-jammed-snake: true
  consumer:
    consumer-id: wordsnake-consumer
    output-file: /tmp/wordsnakes/wordsnakes.txt

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/"
  endpoint:
    health:
      show-details: always