name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    
    # TODO currently not working - got '422 Unprocessable Entity'
    #- name: Deploy with maven
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  run: mvn -B -e -Dmaven.wagon.http.pool=false clean deploy
      
    - name: Deploy to docker registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker build -t kafka_wordsnake . | docker tag kafka_wordsnake docker.pkg.github.com/bekyp/kafka_wordsnake/kafka_wordsnake:latest | docker push docker.pkg.github.com/bekyp/kafka_wordsnake/kafka_wordsnake:latest
